spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/logistics?currentSchema=slack_service # 스키마명 바꾸세요
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
slack:
  base-url: https://slack.com/api
  bot-token: ${SLACK_BOT_TOKEN}