spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/logistics?currentSchema=hub_service
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
