CREATE SCHEMA IF NOT EXISTS delivery_service;

CREATE TABLE IF NOT EXISTS delivery_service.p_delivery_manager (
    delivery_manager_id BIGINT PRIMARY KEY,
    hub_id UUID,
    slack_id VARCHAR(255) NOT NULL,
    manager_type VARCHAR(50) NOT NULL,
    delivery_sequence INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_at TIMESTAMP,
    updated_by BIGINT,
    deleted_at TIMESTAMP,
    deleted_by BIGINT
    );

CREATE TABLE IF NOT EXISTS delivery_service.p_delivery_manager_assignment_state (
    assignment_state_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hub_id UUID,
    manager_type VARCHAR(50) NOT NULL,
    last_assigned_sequence INTEGER NOT NULL,
    last_assigned_manager_id BIGINT
    );

-- hub_id가 있는 경우 (COMPANY_DELIVERY_MANAGER)
CREATE UNIQUE INDEX uk_assignment_state_pool
    ON delivery_service.p_delivery_manager_assignment_state (manager_type, hub_id)
    WHERE hub_id IS NOT NULL;

-- hub_id가 NULL인 경우 (HUB_DELIVERY_MANAGER)
CREATE UNIQUE INDEX uk_assignment_state_pool_global
    ON delivery_service.p_delivery_manager_assignment_state (manager_type)
    WHERE hub_id IS NULL;


CREATE TABLE IF NOT EXISTS delivery_service.p_delivery (
                                                           delivery_id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    order_id UUID NOT NULL UNIQUE,
    start_hub_id UUID NOT NULL,
    end_hub_id UUID NOT NULL,
    company_delivery_manager_id BIGINT,
    status VARCHAR(20) NOT NULL,
    delivery_address VARCHAR(255) NOT NULL,
    receiver_name VARCHAR(100) NOT NULL,
    slack_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL,
    updated_at TIMESTAMP,
    updated_by BIGINT,
    deleted_at TIMESTAMP,
    deleted_by BIGINT
    );

CREATE TABLE IF NOT EXISTS delivery_service.p_delivery_route (
                                                                 delivery_route_id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    delivery_id UUID NOT NULL,
    sequence INTEGER NOT NULL,
    start_hub_id UUID NOT NULL,
    end_hub_id UUID NOT NULL,
    delivery_manager_id BIGINT NOT NULL,
    expected_distance DECIMAL(10,2) NOT NULL CHECK (expected_distance > 0),
    expected_duration INTEGER NOT NULL,
    actual_distance DECIMAL(10,2),
    actual_duration INTEGER,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT NOT NULL,
    updated_at TIMESTAMP,
    updated_by BIGINT,
    deleted_at TIMESTAMP,
    deleted_by BIGINT
    );