CREATE SCHEMA IF NOT EXISTS user_service;
CREATE SCHEMA IF NOT EXISTS slack_service;
CREATE SCHEMA IF NOT EXISTS hub_service;
CREATE SCHEMA IF NOT EXISTS company_service;
CREATE SCHEMA IF NOT EXISTS product_service;
CREATE SCHEMA IF NOT EXISTS inventory_service;
CREATE SCHEMA IF NOT EXISTS order_service;
CREATE SCHEMA IF NOT EXISTS delivery_service;
CREATE SCHEMA IF NOT EXISTS hubroute_service;


CREATE TABLE IF NOT EXISTS company_service.p_company_service(
	company_id UUID PRIMARY KEY,
    hub_id UUID NOT NULL,
    company_name VARCHAR(255) NOT NULL,
    company_address VARCHAR(255) NOT NULL,
    company_type VARCHAR(20) NOT NULL CHECK (company_type IN('PRODUCER', 'RECEIVER')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_at TIMESTAMP,
    updated_by BIGINT,
    deleted_at TIMESTAMP,
    deleted_by BIGINT
);


CREATE TABLE IF NOT EXISTS user_service.p_user (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(10) NOT NULL,
    password VARCHAR(255) NOT NULL,
    slack_id VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    role VARCHAR(30) NOT NULL,
    company_id UUID,
    hub_id UUID,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_at TIMESTAMP,
    updated_by BIGINT,
    deleted_at TIMESTAMP,

    CONSTRAINT uk_user_username UNIQUE (username),
    CONSTRAINT uk_user_slack_id UNIQUE (slack_id),

    CONSTRAINT chk_user_status
     CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),

    CONSTRAINT chk_user_role
     CHECK (
         role IN (
                  'MASTER',
                  'HUB_MANAGER',
                  'HUB_DELIVERY_MANAGER',
                  'COMPANY_MANAGER',
                  'COMPANY_DELIVERY_MANAGER'
             )
         ),
    deleted_by BIGINT
);

CREATE TABLE IF NOT EXISTS hub_service.p_hub (
    hub_id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    hub_name    VARCHAR(100)   NOT NULL,
    hub_address VARCHAR(255)   NOT NULL,
    latitude    DECIMAL(10, 7) NOT NULL,
    longitude   DECIMAL(10, 7) NOT NULL,
    created_at  TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by  BIGINT         NOT NULL,
    updated_at  TIMESTAMP      NULL,
    updated_by  BIGINT         NULL,
    deleted_at  TIMESTAMP      NULL,
    deleted_by  BIGINT         NULL
    );

CREATE TABLE IF NOT EXISTS delivery_service.p_delivery_manager (
    delivery_manager_id BIGINT PRIMARY KEY,
    hub_id UUID,
    slack_id VARCHAR(255) NOT NULL,
    manager_type VARCHAR(50) NOT NULL,
    delivery_sequence INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_at TIMESTAMP,
    updated_by BIGINT,
    deleted_at TIMESTAMP,
    deleted_by BIGINT
    );