CREATE SCHEMA IF NOT EXISTS user_service;
CREATE SCHEMA IF NOT EXISTS slack_service;

CREATE TABLE IF NOT EXISTS user_service.p_user (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(10) NOT NULL,
    password VARCHAR(255) NOT NULL,
    slack_id VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    role VARCHAR(30) NOT NULL,
    company_id UUID,
    hub_id UUID,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_at TIMESTAMP,
    updated_by BIGINT,
    deleted_at TIMESTAMP,
    deleted_by BIGINT,

    CONSTRAINT chk_user_status
    CHECK (
              status IN (
              'PENDING',
              'APPROVED',
              'REJECTED'
                        )
    ),

    CONSTRAINT chk_user_role
    CHECK (
              role IN (
              'MASTER',
              'HUB_MANAGER',
              'HUB_DELIVERY_MANAGER',
              'COMPANY_MANAGER',
              'COMPANY_DELIVERY_MANAGER'
                      )
    )
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_user_username_active
    ON user_service.p_user (username)
    WHERE deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uk_user_slack_id_active
    ON user_service.p_user (slack_id)
    WHERE deleted_at IS NULL;