server:
  # 외부 요청이 가장 먼저 들어오는 Gateway 포트
  port: 19091

spring:
  application:
    # Eureka에 등록될 서비스 이름
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          # Eureka 서비스 이름을 외부 URL에 노출하는 자동 라우팅은 사용하지 않음
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true

          # 외부 요청 경로와 내부 서비스를 직접 연결
          routes:
            - id: user-service

              # lb는 LoadBalancer를 의미
              # Eureka에서 template-service의 실행 위치를 조회해 요청을 전달
              uri: lb://user-service

              predicates:
                # 이 경로로 들어온 요청만 template-service로 전달
                - Path=/api/v1/users/**,/api/v1/auth/**
eureka:
  client:
    service-url:
      # Gateway가 접속할 Eureka Server 주소
      defaultZone: http://localhost:19090/eureka/

  instance:
    # 호스트명 대신 IP 주소를 Eureka에 등록
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        # 상태 확인용 Actuator 엔드포인트 공개
        include: health,info,gateway

  endpoint:
    gateway:
      # Gateway 라우트 조회만 허용
      # 운영에서도 unrestricted보다 read-only가 안전
      access: read-only

    health:
      # 상세 상태 정보 표시
      show-details: always