spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/logistics?currentSchema=ai_service # 스키마명 바꾸세요
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  rabbitmq:
    # .env의 RABBITMQ_HOST(=rabbitmq)는 도커 네트워크 안에서만 유효하다
    host: localhost
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

rabbitmq:
  order-created:
    exchange: order.exchange
    queue: order-created.queue

    dlx: ai.dead-letter.exchange
    dlq: order-created.dlq
    dlq-routing-key: order-created.dead

  slack:
    exchange: slack.exchange
    queue: slack.send.queue
    routing-key: slack.send

ai:
  gemini:
    url: https://generativelanguage.googleapis.com/v1beta/models
    key: ${GEMINI_KEY}
