spring:
  application:
    name: user-service
  profiles:
    active: local

server:
  port: 19092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

jwt:
  secret: ${JWT_SECRET:local-jwt-secret-key-must-be-at-least-32-bytes-long} # 추후 Gateway에서 해당 secret으로 검증
  access-token-expiration-seconds: 1800 #만료 시간 30분
  refresh-token-expiration-seconds: 1209600 #만료 시간 14일