spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/logistics?currentSchema=user_service
    username: ${DB_USERNAME:logistics}
    password: ${DB_PASSWORD:logistics}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
