spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/logistics?currentSchema=user_service
    username: ${DB_USERNAME:logistics}
    password: ${DB_PASSWORD:logistics}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true

eureka:
  instance:
    # 로컬 Windows 호스트명 대신 실제 IP를 Eureka에 등록한다.
    prefer-ip-address: true

    # Eureka 화면에서 인스턴스를 구분하기 쉽게 설정
    instance-id: ${spring.application.name}:${server.port}

jwt:
  secret: ${JWT_SECRET:local-jwt-secret-key-must-be-at-least-32-bytes-long} # 추후 Gateway에서 해당 secret으로 검증

app:
  master:
    username: ${MASTER_USERNAME}
    name: ${MASTER_NAME}
    password: ${MASTER_PASSWORD}
    slack-id: ${MASTER_SLACK_ID}