spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/logistics?currentSchema=order_service
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  data:
    redis:
      host: localhost
      port: 6379

  rabbitmq:
    # .env의 RABBITMQ_HOST(=rabbitmq)는 도커 네트워크 안에서만 유효하다
    host: localhost
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
