spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: product-service # 서비스명 컨벤션대로 바꾸세요 (예: order-service)
  profiles:
    active: prod

server:
  port: 19094 # 컨벤션 포트표 참고해서 바꾸세요 (19090부터 순서대로 배정됨)

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:19090/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
