spring:
  application:
    name: hubRoute-service # 서비스명 컨벤션대로 바꾸세요 (예: order-service)
  profiles:
    active: local
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

server:
  port: 19100 # 컨벤션 포트표 참고해서 바꾸세요 (19090부터 순서대로 배정됨)

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: http://localhost:9411/api/v2/spans
