spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/logistics?currentSchema=delivery_service
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
